# Generated by Django 3.0.3 on 2020-07-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_password_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduserprofileinfo',
            old_name='end_user',
            new_name='user',
        ),
    ]
